Integration tests
HSLdevcom/jore4-auth pull request #5
Opened 2021-06-18 13:49 UTC by jschummer

2021-06-24 09:22 UTC, tk-vincit reviewed
I'm not Java/Kotlin expert, but this looks good to me. If possible, someone else should approve.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-:-McxJos_55vatOQ-p3Vm:bq30as5)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @jschummer)

___
*[pom.xml, line 60 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxE3sw6vPX6BJeEqoQ:-McxE3sw6vPX6BJeEqoR:bkwnrru) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/pom.xml#L60)):*
> ```XML
>         </profile>
>         <profile>
>             <id>all-tests</id>
> ```

Not sure if I misunderstood something, but looks that in `all-tests` node we are SKIPPING unit tests and integration tests?
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxF63g4P2V843WCksD:-McxF63h9zNYvZ7YFR1x:b-opelwl) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt#L2)):*
> ```Kotlin
> package fi.hsl.jore4.auth
> ```

This file is full of more or less random id's and secrets. Should we comment or document somewhere where these do come from?
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCCodeExchangeApiControllerTest.kt, line 121 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxIpU140s6WRsyKaKC:-McxIpU140s6WRsyKaKD:b-kmx472) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCCodeExchangeApiControllerTest.kt#L121)):*
> ```Kotlin
>     @DisplayName("Should invoke code exchange endpoint")
>     fun shouldInvokeCodeExchangeEndpoint() {
>         val someAuthCode = "randomCodeMayNotBeValid"
> ```

Not sure what conventions kotlin has, but should this be `const val`? (also plenty of other plain `val`s in this PR.)


<!-- Sent from Reviewable.io -->

2021-06-24 10:51 UTC, lassemaatta reviewed
> Reviewed 13 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/5)* status: 13 of 16 files reviewed, 5 unresolved discussions (waiting on @jschummer and @tk-vincit)

___
*[pom.xml, line 26 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxZBiJEV7xmoGGtTap:-McxZBiJEV7xmoGGtTaq:bk34h1i) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/pom.xml#L26)):*
> ```XML
> 
>         <!-- Only unit tests are run by default. -->
>         <skip.integration.tests>true</skip.integration.tests>
> ```

Is this really necessary? Do the integration tests really take so long?
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxF63g4P2V843WCksD:-Mcx_47F3E25qszhU4Wp:b-wdjfrv) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt#L2)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This file is full of more or less random id's and secrets. Should we comment or document somewhere where these do come from?
</blockquote></details>

I've often used something like `new UUID().toString()` (perhaps implemented in a  `randomString()` method) when generating random strings instead of using some `asdasdas123`.
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt, line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-Mcx_NxgD-zeNyDy1TjW:-Mcx_NxgD-zeNyDy1TjX:b-yf4xbn) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt#L35)):*
> ```Kotlin
>     const val OIDC_PROVIDER_END_SESSION_ENDPOINT_PATH = "/test-openid/logout"
> 
>     const val OIDC_PROVIDER_DISCOVERY_CONTENT = """
> ```

Could these be just plain `.json` files under `src/test/resources` or do these actually have some dynamic content?


<!-- Sent from Reviewable.io -->

2021-06-24 11:29 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/5)* status: 13 of 16 files reviewed, 7 unresolved discussions (waiting on @jschummer and @tk-vincit)

___
*[pom.xml, line 52 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-Mcxlbv0B9vTteFRSmrF:-Mcxlbv0B9vTteFRSmrG:b9b5jyh) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/pom.xml#L52)):*
> ```XML
>         </profile>
>         <profile>
>             <id>integration-test</id>
> ```

could you add a section to the README how to run these tests?
___
*[pom.xml, line 55 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-Mcxlg-q4u8bRlqWvsBf:-Mcxlg-q4u8bRlqWvsBg:b-t7pn6) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/pom.xml#L55)):*
> ```XML
>             <properties>
>                 <build.profile.id>integration-test</build.profile.id>
>                 <skip.integration.tests>false</skip.integration.tests>
> ```

could you create a github workflow to run these tests on CI?

If you haven't done anything like this before: Just create a folder `.github/workflows` in the repo and add a yaml describing the job(s) you want to run. Example here: https://github.com/HSLdevcom/jore4-ui/blob/main/.github/workflows/ci.yml


<!-- Sent from Reviewable.io -->

2021-06-24 12:20 UTC, jarkkoka reviewed
> Reviewed 11 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/5)* status: 15 of 16 files reviewed, 16 unresolved discussions (waiting on @jschummer and @tk-vincit)

___
*[pom.xml, line 64 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-Mcx5J-H1lKcdywGcRwt:-Mcx5J-H1lKcdywGcRwu:bonbkom) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/pom.xml#L64)):*
> ```
>                 <skip.integration.tests>true</skip.integration.tests>
>                 <skip.unit.tests>true</skip.unit.tests>
> ```

Should there be `false`s instead?
___
*[profiles/integration-test/config.properties, line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxAor7BUwnc0BrS3vu:-McxAor7BUwnc0BrS3vv:bgn6li0) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/profiles/integration-test/config.properties#L36)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> # URL to which to return after login
> # In the dev profile, this should point to a URL served by the frontend dev server
> loginpage.url=https://mylogin.myhost.mydomain:5678
> # URL to which to return after logout
> # In the dev profile, this should point to a URL served by the frontend dev server
> logoutpage.url=https://mylogout.myhost.mydomain:9012
> ```
</details>


Might be an irrelevant remark but aren't these parameters coupling authentication service tightly with a frontend server. Could this authentication service be opened for wider audience (in a further commit) by letting the caller pass the login and logout URLs?
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxCOXu9vE5vZMozNFk:-McxCOXu9vE5vZMozNFl:b-mags8g) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt#L16)):*
> ```
>     const val OIDC_CLIENT_ID = "123456789clientId"
>     const val OIDC_CLIENT_SECRET = "clientSecret012345"
> ```

Hmmm... Aren't these (and likely some other constants as well) already defined in config.properties (in profiles/integration-test folder)? There seems to be redundancy if I am not mistaken. Can you elaborate a little bit about this?
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/MockOIDCProvider.kt, line 53 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxrUAiDRk4OwdMo329:-McxrUAiDRk4OwdMo32A:b-71eqgu) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/MockOIDCProvider.kt#L53)):*
> ```
> "application/json"
> ```

You could use `MediaType.APPLICATION_JSON_VALUE` (from spring-web jar) constant here and below in order to avoid typos.
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/TestTags.kt, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-Mcx5jSa8EPxa22D3MAl:-Mcx5jSa8EPxa22D3MAm:b-76ke43) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/TestTags.kt#L4)):*
> ```
> class TestTags {
>     companion object {
> ```

Could be replaced with plain object (class + companion object).
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCApiRequestBuilder.kt, line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-Mcx9W8Q7rSxdE7I1hka:-Mcx9W8Q7rSxdE7I1hkb:b9lscu6) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCApiRequestBuilder.kt#L18)):*
> ```
> "/public/v1/logout"
> ```

This could be extracted into companion objects as constant. 
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCApiRequestBuilder.kt, line 30 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-Mcx9A7z-P2eDS1Kkvo_:-Mcx9A8-DmHjEol2ydyV:bni6y7c) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCApiRequestBuilder.kt#L30)):*
> ```
>         if (session != null) requestBuilder = requestBuilder.session(session)
>         return requestBuilder
> ```

In more idiomatic form:

```
    return session?.let { requestBuilder.session(it) } ?: requestBuilder
```
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCCodeExchangeApiControllerTest.kt, line 51 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-Mcxtumf56Go_HLXBoyz:-McxtrW0EKKYkFJgUd_U:b-1crmbl) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCCodeExchangeApiControllerTest.kt#L51)):*
> ```
>     @Nested
> ```

Nice. :+1: 
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCLogoutApiControllerTest.kt, line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-Mcxw_3vC3U3oitOisne:-Mcxw_3w2vZiENoktFxJ:bbumpo0) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCLogoutApiControllerTest.kt#L35)):*
> ```
> OIDCLogoutApiControllerTest
> ```

Nice tests. :+1: 


<!-- Sent from Reviewable.io -->

2021-06-25 09:07 UTC, jschummer reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/5)* status: 15 of 16 files reviewed, 16 unresolved discussions (waiting on @jarkkoka, @lassemaatta, @pallost, and @tk-vincit)

___
*[pom.xml, line 26 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxZBiJEV7xmoGGtTap:-McyRiMYATJbbNgLNWyu:b-hlxdp3) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/pom.xml#L26)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Is this really necessary? Do the integration tests really take so long?
</blockquote></details>

Well, spinning up wire mock can take some seconds. Not sure if it is _really_ _really_ necessary at this stage, but I'd rather have them run separately from the build process.
___
*[pom.xml, line 52 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-Mcxlbv0B9vTteFRSmrF:-Md1GH0J2edUW6Q4eEFL:b3erh2m) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/pom.xml#L52)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could you add a section to the README how to run these tests?
</blockquote></details>

Yes, good idea. Added now.
___
*[pom.xml, line 55 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-Mcxlg-q4u8bRlqWvsBf:-McyRwP04F0L8RYN3hOP:b-so4y8f) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/pom.xml#L55)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could you create a github workflow to run these tests on CI?

If you haven't done anything like this before: Just create a folder `.github/workflows` in the repo and add a yaml describing the job(s) you want to run. Example here: https://github.com/HSLdevcom/jore4-ui/blob/main/.github/workflows/ci.yml
</blockquote></details>

Originally, I was planning to have you do that ;-) But I can gave it a shot, and added a workflow file now :-)
___
*[pom.xml, line 60 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxE3sw6vPX6BJeEqoQ:-McyS0Jn2FUhxeuAuj-l:b-kj65li) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/pom.xml#L60)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Not sure if I misunderstood something, but looks that in `all-tests` node we are SKIPPING unit tests and integration tests?
</blockquote></details>

Good point! These seem to have gotten mixed up.
___
*[pom.xml, line 64 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-Mcx5J-H1lKcdywGcRwt:-McyTXw89bMzrydXzrME:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/pom.xml#L64)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>                 <skip.integration.tests>true</skip.integration.tests>
>                 <skip.unit.tests>true</skip.unit.tests>
> ```

Should there be `false`s instead?
</blockquote></details>

Done.
___
*[profiles/integration-test/config.properties, line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxAor7BUwnc0BrS3vu:-McyT_pc3WhUO6iqTt2G:b813l23) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/profiles/integration-test/config.properties#L36)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> # URL to which to return after login
> # In the dev profile, this should point to a URL served by the frontend dev server
> loginpage.url=https://mylogin.myhost.mydomain:5678
> # URL to which to return after logout
> # In the dev profile, this should point to a URL served by the frontend dev server
> logoutpage.url=https://mylogout.myhost.mydomain:9012
> ```

Might be an irrelevant remark but aren't these parameters coupling authentication service tightly with a frontend server. Could this authentication service be opened for wider audience (in a further commit) by letting the caller pass the login and logout URLs?
</blockquote></details>

This is a good point and actually that was the original plan (to let the caller pass a redirect-parameter).

For context, this is how it _could_ have worked:

1. frontend redirects user to auth backend, passes frontend-redirect-paremeter, e.g. `?frontend_redirect=https://jore.frontend/bla`
2. auth backend redirects user to oidc provider sign in page, passes backend-redirect-parameter, which contains the frontend-redirect-paremeter, e.g. `?redirect_uri=https://jore.auth.backend/blub?original_frontend_redirect=https%3A%2F%2Fjore.frontend%2Fbla`
3. oidc provider redirects back the auth backend to the redirect url passed as `redirect_uri` (containing the encoded `frontend_redirect`)
4. auth backend redirects back to the frontend to the redirect url passed as `original_frontend_redirect`

Unfortunately, as I had to learn, OIDC requires the `redirect_uri` to be fully constant, i.e. it is not possible to pass an own redirect uri in a parameter of the redirect uri passed to the oidc provider dynamically. This is why the loginpage has to be defined statically :-( (This is, however, different in OAuth 2.0, there this kind of mechanism is perfectly possible.)

These definitions should (and will be) overwritten using environment variables in our cloud environments, so we keep the coupling as loose as possible.
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxF63g4P2V843WCksD:-McyVT5-ETajx1SntX1w:bhu9r1g) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt#L2)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

I've often used something like `new UUID().toString()` (perhaps implemented in a  `randomString()` method) when generating random strings instead of using some `asdasdas123`.
</blockquote></details>

These need to match the values provided in the config.properties file, therefore I don't think it is possible to generate these on the fly.
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxCOXu9vE5vZMozNFk:-McyVcz9AZ6LuwqMLv7F:b-7rkhg8) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt#L16)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>     const val OIDC_CLIENT_ID = "123456789clientId"
>     const val OIDC_CLIENT_SECRET = "clientSecret012345"
> ```

Hmmm... Aren't these (and likely some other constants as well) already defined in config.properties (in profiles/integration-test folder)? There seems to be redundancy if I am not mistaken. Can you elaborate a little bit about this?
</blockquote></details>

Yes, they are duplicated, and for a reason:

The application gets its property values through the `application.properties` definitions. Reading the properties is part of the application logic.

If the integration tests would read the values through the same mechanism, potential errors could not be caught by the tests. If e.g. some string would be read from the property definitions in a wrong way, the tests would contain the same error and comparing the read property value to the assumed value would give a green light even though both were read wrong.

This is why I'd prefer to have these assumed values defined statically in the code at compile time. Does that sound reasonable?

But... you do have a point that this information should be at least put in a comment next to those constants. I added a comment now.
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt, line 35 at [...]

2021-06-25 10:43 UTC, lassemaatta reviewed
> Reviewed 1 of 17 files at r2, 7 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/5)* status: 8 of 19 files reviewed, 15 unresolved discussions (waiting on @jarkkoka, @jschummer, @lassemaatta, @pallost, and @tk-vincit)

___
*[pom.xml, line 26 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxZBiJEV7xmoGGtTap:-Md1kW7eByu35eF7QEBM:baqk87r) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/pom.xml#L26)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Well, spinning up wire mock can take some seconds. Not sure if it is _really_ _really_ necessary at this stage, but I'd rather have them run separately from the build process.
</blockquote></details>

Okay. I just have some bad memories of this. I've never seen a project where the integration tests take more than a few minutes. On the other hand I've seen a few projects where the developers (because they didn't know) or CI (due to bugs in scripts) _never_ ran the integrations tests at all and all the integration tests were horribly broken because no-one ever checked if they worked or fixed them when doing changes :(
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxCOXu9vE5vZMozNFk:-Md1g2HlEBgJdbXAnwUb:b-6l0hv3) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt#L16)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Yes, they are duplicated, and for a reason:

The application gets its property values through the `application.properties` definitions. Reading the properties is part of the application logic.

If the integration tests would read the values through the same mechanism, potential errors could not be caught by the tests. If e.g. some string would be read from the property definitions in a wrong way, the tests would contain the same error and comparing the read property value to the assumed value would give a green light even though both were read wrong.

This is why I'd prefer to have these assumed values defined statically in the code at compile time. Does that sound reasonable?

But... you do have a point that this information should be at least put in a comment next to those constants. I added a comment now.
</blockquote></details>

I think Jörg has a valid concern, regarding possible bugs in the way the properties are read. However, I'm not sure if this is the best way to deal with it. If you imagine a scenario where some code change causes minor breakage in some of the properties, then it might be really difficult for the developer to realize the exact problem if the only symptom is that some `shouldRedirectUserToOIDCEndSessionEndpoint` test suddenly fails. 

One way to tackle this would be to 
1. provide an abstraction over the properties (see e.g. how the jore3 importer does this [link](https://github.com/HSLdevcom/jore4-jore3-importer/blob/master/src/main/java/fi/hsl/jore/importer/config/properties/DestinationDataSourceProperties.java)), 
1. (optional) add tests that verify that reading the properties works (if you feel like there's a risk of bugs)
1. use the abstraction in integration tests to parse the properties and supply them to the mock classes


But I'll leave it up to you to decide what to do.


<!-- Sent from Reviewable.io -->

2021-07-20 09:54 UTC, jschummer reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/5)* status: 1 of 21 files reviewed, 15 unresolved discussions (waiting on @jarkkoka, @lassemaatta, @pallost, and @tk-vincit)

___
*[pom.xml, line 26 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxZBiJEV7xmoGGtTap:-Mf2JdCJ0MOTPIhTHyKx:b-bfypyx) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/pom.xml#L26)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Okay. I just have some bad memories of this. I've never seen a project where the integration tests take more than a few minutes. On the other hand I've seen a few projects where the developers (because they didn't know) or CI (due to bugs in scripts) _never_ ran the integrations tests at all and all the integration tests were horribly broken because no-one ever checked if they worked or fixed them when doing changes :(
</blockquote></details>

:-/ Luckily, I've not had to deal with this kind of situation.

Now that the CI runs the tests successfully, could we trust they'll be run in the CI? That way developers will also run them in case the CI does not let their changes through.
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxCOXu9vE5vZMozNFk:-Mf2KLClBf37rsGXSx1v:b-ixc5g9) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt#L16)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

I think Jörg has a valid concern, regarding possible bugs in the way the properties are read. However, I'm not sure if this is the best way to deal with it. If you imagine a scenario where some code change causes minor breakage in some of the properties, then it might be really difficult for the developer to realize the exact problem if the only symptom is that some `shouldRedirectUserToOIDCEndSessionEndpoint` test suddenly fails. 

One way to tackle this would be to 
1. provide an abstraction over the properties (see e.g. how the jore3 importer does this [link](https://github.com/HSLdevcom/jore4-jore3-importer/blob/master/src/main/java/fi/hsl/jore/importer/config/properties/DestinationDataSourceProperties.java)), 
1. (optional) add tests that verify that reading the properties works (if you feel like there's a risk of bugs)
1. use the abstraction in integration tests to parse the properties and supply them to the mock classes


But I'll leave it up to you to decide what to do.


</blockquote></details>

Well, the code base of the auth backend is sufficiently small, so I'd maybe just leave it the way it is, with some duplication of test data. Could we live with that?


<!-- Sent from Reviewable.io -->

2021-08-11 07:31 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/5)* status: 0 of 21 files reviewed, 13 unresolved discussions (waiting on @jarkkoka, @jschummer, @lassemaatta, and @tk-vincit)

___
*[pom.xml, line 60 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxE3sw6vPX6BJeEqoQ:-Mgo5j1v3XpzTcAX6jAH:bb6ywmx) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/pom.xml#L60)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Good point! These seem to have gotten mixed up.
</blockquote></details>

LGTM
___
*[pom.xml, line 64 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-Mcx5J-H1lKcdywGcRwt:-Mgo5mV1-mnQfuBLs3xf:bb6ywmx) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/pom.xml#L64)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM
___
*[profiles/integration-test/config.properties, line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxAor7BUwnc0BrS3vu:-Mgo6AU01gR9jsuaZBkU:b7ylw2s) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/profiles/integration-test/config.properties#L36)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

This is a good point and actually that was the original plan (to let the caller pass a redirect-parameter).

For context, this is how it _could_ have worked:

1. frontend redirects user to auth backend, passes frontend-redirect-paremeter, e.g. `?frontend_redirect=https://jore.frontend/bla`
2. auth backend redirects user to oidc provider sign in page, passes backend-redirect-parameter, which contains the frontend-redirect-paremeter, e.g. `?redirect_uri=https://jore.auth.backend/blub?original_frontend_redirect=https%3A%2F%2Fjore.frontend%2Fbla`
3. oidc provider redirects back the auth backend to the redirect url passed as `redirect_uri` (containing the encoded `frontend_redirect`)
4. auth backend redirects back to the frontend to the redirect url passed as `original_frontend_redirect`

Unfortunately, as I had to learn, OIDC requires the `redirect_uri` to be fully constant, i.e. it is not possible to pass an own redirect uri in a parameter of the redirect uri passed to the oidc provider dynamically. This is why the loginpage has to be defined statically :-( (This is, however, different in OAuth 2.0, there this kind of mechanism is perfectly possible.)

These definitions should (and will be) overwritten using environment variables in our cloud environments, so we keep the coupling as loose as possible.
</blockquote></details>

I don't think this is true, you do can define a redirect_uri dynamically. You just need to make sure that the OIDC client is configured such that it allows a wildcard of addresses to redirect to. E.g. `https://dev.jore.hsl.fi/*`
Nevertheless, I don't think this is an issue as we only have a single frontend. If this becomes an issue with the frontend routing, we can fix this later.
___
*[src/main/kotlin/fi/hsl/jore4/auth/oidc/OIDCCodeExchangeService.kt, line 82 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-Mcxmv_LDrs-J8ini8WR:-Mcxmv_MBzqfeMEuOl32:bbh1o30) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/main/kotlin/fi/hsl/jore4/auth/oidc/OIDCCodeExchangeService.kt#L82)):*
> ```Kotlin
> 
>         // redirect the user to the login page URL
>         val redirectUri = URI.create(loginPageUrl)
> ```

not in the scope of the PR, but loginPageUrl is quite misunderstandable here. What we need here is "landing page after logging in". Should be called LOGIN_LANDING_PAGE_URL?


<!-- Sent from Reviewable.io -->

2021-08-11 07:35 UTC, pallost reviewed
> Dismissed @jarkkoka from 7 discussions.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/5)* status: 0 of 21 files reviewed, 4 unresolved discussions (waiting on @jarkkoka, @jschummer, and @lassemaatta)

___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxF63g4P2V843WCksD:-Mgo752P-t78jwc9KvVC:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt#L2)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

These need to match the values provided in the config.properties file, therefore I don't think it is possible to generate these on the fly.
</blockquote></details>

OK
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxCOXu9vE5vZMozNFk:-Mgo7-Kw4MnwTkW83w1v:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/Constants.kt#L16)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Well, the code base of the auth backend is sufficiently small, so I'd maybe just leave it the way it is, with some duplication of test data. Could we live with that?
</blockquote></details>

OK
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/MockOIDCProvider.kt, line 53 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxrUAiDRk4OwdMo329:-Mgo79do2AzoYkzAW40b:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/MockOIDCProvider.kt#L53)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Good point, changed it.
</blockquote></details>

OK
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/TestTags.kt, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-Mcx5jSa8EPxa22D3MAl:-Mgo7F0M9oM9ILSeyExf:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/TestTags.kt#L4)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

True, changed it!
</blockquote></details>

OK
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCApiRequestBuilder.kt, line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-Mcx9W8Q7rSxdE7I1hka:-Mgo7Z1sBNwEeDh5igZP:bb6ywmx) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCApiRequestBuilder.kt#L18)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Do you think it is necessary / good style? There is no duplication here and that constant is pretty much the only thing which this function defines.
</blockquote></details>

LGTM
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCApiRequestBuilder.kt, line 30 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-Mcx9A7z-P2eDS1Kkvo_:-Mgo7Qjg6nim5UiMq7u4:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCApiRequestBuilder.kt#L30)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Nice one :-) I have to admit, I never really got used to `let`...

Changed it :+1: 
</blockquote></details>

OK
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCCodeExchangeApiControllerTest.kt, line 51 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-Mcxtumf56Go_HLXBoyz:-Mgo7dFw0BYfla5rUA9E:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCCodeExchangeApiControllerTest.kt#L51)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCCodeExchangeApiControllerTest.kt, line 121 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxIpU140s6WRsyKaKC:-Mgo7bIs5SIEb5P0lkvI:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCCodeExchangeApiControllerTest.kt#L121)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

It's not possible to make `const`s out of local variables in Kotlin. They should be compile-time constants in class scope to be `const`.
</blockquote></details>

OK
___
*[src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCLogoutApiControllerTest.kt, line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-Mcxw_3vC3U3oitOisne:-Mgo7fXV5izhz0aDx-yU:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/src/integration-test/kotlin/fi/hsl/jore4/auth/apipublic/v1/OIDCLogoutApiControllerTest.kt#L35)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2021-08-11 07:36 UTC, pallost approved these changes
> Dismissed @jarkkoka from a discussion.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/5)* status: 0 of 21 files reviewed, 3 unresolved discussions (waiting on @jarkkoka, @jschummer, and @lassemaatta)

___
*[profiles/integration-test/config.properties, line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/5#-McxAor7BUwnc0BrS3vu:-Mgo7v2xDtFzdzA6lAlW:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/3a33a97066e974d76a06b6911ecf686486be43f5/profiles/integration-test/config.properties#L36)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I don't think this is true, you do can define a redirect_uri dynamically. You just need to make sure that the OIDC client is configured such that it allows a wildcard of addresses to redirect to. E.g. `https://dev.jore.hsl.fi/*`
Nevertheless, I don't think this is an issue as we only have a single frontend. If this becomes an issue with the frontend routing, we can fix this later.
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2021-08-11 11:50 UTC, merged